# Generated by Django 4.1.4 on 2022-12-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=12, unique=True, verbose_name='Артикул'),
        ),
    ]
