version: '3.7'

services:

  backend:
    depends_on:
      - psql
    ports:
      - ${APP_PORT}:${APP_PORT}


  psql:
    image: postgres:alpine
    ports:
      - "5440:5432"
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}

volumes:
  psql_data: { }